# Agent Configuration

# Base paths for agent operation
paths:
  # Memory storage location - where all agent memory will be stored
  memory_dir: /home/agheieff/AgentMemory
  
  # Projects directory - where code projects will be managed
  projects_dir: /home/agheieff/Projects
  
  # Temporary file storage
  temp_dir: ${memory_dir}/temp
  
  # Backup directory for agent memory
  backup_dir: ${memory_dir}/backups

# Memory system configuration
memory:
  # Maximum size for indexed documents in bytes (1MB)
  max_document_size: 1048576
  
  # Maximum number of entries in vector index
  max_indexed_entries: 10000
  
  # Maximum number of backups to keep
  max_backups: 10
  
  # Backup interval in seconds (1 hour)
  backup_interval: 3600
  
  # Context keys to track
  context_keys:
    - system_config
    - tool_usage
    - error_history
    - active_projects
    - agent_notes
    - status_updates
    - command_skills
    - knowledge_base
    - important
    - task
    - mind_map
    - code
    - project

# LLM model configuration
llm:
  # Default model to use
  default_model: deepseek
  
  # Available models
  models:
    - anthropic
    - deepseek
  
  # Model-specific settings
  anthropic:
    temperature: 0.7
    max_tokens: 4000
  
  deepseek:
    temperature: 0.7
    max_tokens: 4000

# Agent behavior configuration
agent:
  # Whether to run in headless mode (no interactive prompts)
  headless: false
  
  # Whether to run in test mode (no actual commands executed)
  test_mode: false
  
  # Maximum inactivity time in seconds before agent auto-terminates (1 hour)
  max_inactivity: 3600
  
  # Whether to allow internet access
  allow_internet: true
  
  # Maximum number of tasks to track
  max_tasks: 100
  
  # Whether to do periodic system resource monitoring
  monitor_resources: true
  
  # Resource monitoring interval in seconds
  resource_check_interval: 300

# Security settings
security:
  # Directories that are off-limits for the agent
  restricted_dirs:
    - /etc
    - /var
    - /boot
    - /root
  
  # Commands that are always blocked
  blocked_commands:
    - rm -rf /
    - mkfs
    - dd
    - wget
    - curl
    - sudo
  
  # Maximum file size the agent can create/modify (100MB)
  max_file_size: 104857600

# Internet tools configuration
internet:
  # Web client configuration
  web_client:
    # Default user agent string
    user_agent: "Agent Research Tool/1.0"
    
    # Default request timeout in seconds
    timeout: 30
    
    # Optional proxy settings
    # proxy:
    #   http: http://proxy.example.com:8080
    #   https: https://proxy.example.com:8080
  
  # Search engine configuration
  search_engine:
    # Default search engine to use
    default_engine: duckduckgo
    
    # API keys for various search engines
    api_keys:
      google:
        api_key: ""  # Add your Google API key here
        cse_id: ""   # Add your Google Custom Search Engine ID here
      bing:
        api_key: ""  # Add your Bing API key here
    
    # Rate limiting settings to prevent API abuse
    rate_limits:
      duckduckgo:
        requests_per_hour: 100
        seconds_between_requests: 2
      google:
        requests_per_day: 100
        seconds_between_requests: 1
      bing:
        requests_per_month: 1000
        seconds_between_requests: 1
  
  # Research tool settings
  research:
    # Default engines to use for research
    engines:
      - duckduckgo
    
    # Default depth for research (how many links deep to follow)
    default_depth: 1
    
    # Default maximum pages to visit per depth level
    default_max_pages: 3
    
    # Cache settings
    cache_size_limit: 100
    
    # Download settings
    download_dir: ${memory_dir}/downloads

# Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: INFO
  
  # Whether to log to file
  log_to_file: true
  
  # Log file path
  log_file: ${memory_dir}/logs/agent.log
  
  # Whether to log command executions
  log_commands: true
  
  # Format for log entries
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
