agent:
  allow_internet: true
  headless: false
  max_inactivity: 3600
  max_tasks: 100
  monitor_resources: true
  resource_check_interval: 300
  test_mode: false
internet:
  research:
    cache_size_limit: 100
    default_depth: 1
    default_max_pages: 3
    download_dir: None/downloads
    engines:
    - duckduckgo
  search_engine:
    api_keys:
      bing:
        api_key: ''
      google:
        api_key: ''
        cse_id: ''
    default_engine: duckduckgo
    rate_limits:
      bing:
        requests_per_month: 1000
        seconds_between_requests: 1
      duckduckgo:
        requests_per_hour: 100
        seconds_between_requests: 2
      google:
        requests_per_day: 100
        seconds_between_requests: 1
  web_client:
    timeout: 30
    user_agent: Agent Research Tool/1.0
llm:
  anthropic:
    max_tokens: 4000
    temperature: 0.7
  deepseek:
    max_tokens: 4000
    temperature: 0.7
  default_model: deepseek
  models:
  - anthropic
  - deepseek
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_commands: true
  log_file: None/logs/agent.log
  log_to_file: true
memory:
  backup_interval: 3600
  context_keys:
  - system_config
  - tool_usage
  - error_history
  - active_projects
  - agent_notes
  - status_updates
  - command_skills
  - knowledge_base
  - important
  - task
  - mind_map
  - code
  - project
  max_backups: 10
  max_document_size: 1048576
  max_indexed_entries: 10000
paths:
  backup_dir: None/backups
  memory_dir: /home/agheieff/AgentMemory
  projects_dir: /home/agheieff/Projects
  temp_dir: None/temp
security:
  blocked_commands:
  - rm -rf /
  - mkfs
  - dd
  - wget
  - curl
  - sudo
  max_file_size: 104857600
  restricted_dirs:
  - /etc
  - /var
  - /boot
  - /root
