paths:
  projects_dir: projects
llm:
  default_model: deepseek
  models:
    - anthropic
    - deepseek
  anthropic:
    temperature: 0.7
    max_tokens: 4000
  deepseek:
    temperature: 0.7
    max_tokens: 4000
agent:
  headless: false
  test_mode: false
  max_inactivity: 3600
  allow_internet: true
logging:
  level: INFO
  log_to_file: true
  log_file: Config/agent.log
  log_commands: true
